export default {
    meilisearchUrl:         process.env.NEXT_PUBLIC_MEILISEARCH_URL || 'http://127.0.0.1:7700',
    meilisearchMasterKey:   process.env.NEXT_PUBLIC_MEILISEARCH_MASTER_KEY || 'masterKey',
    meilisearchDocument:    process.env.NEXT_PUBLIC_MEILISEARCH_DEFAULT_DOCUMENT_NAME || 'points',
    dataforseo_token:       process.env.NEXT_PUBLIC_DATAFORSEO_TOKEN || '',
    dataforseo_url:         process.env.NEXT_PUBLIC_DATAFORSEO_URL || '',
    authorized_origins:     process.env.NEXT_PUBLIC_AUTHORIZED_ORIGINS || '',
    diffbot_token:          process.env.NEXT_PUBLIC_DIFFBOT_TOKEN || '',
    diffbot_url:            process.env.NEXT_PUBLIC_DIFFBOT_URL || '',
    diffbot_kg_url:         process.env.NEXT_PUBLIC_DIFFBOT_KG_URL || '',
    google_sheet_id:        process.env.NEXT_PUBLIC_GOOGLE_SHEET_ID || '',
    google_api_token:       process.env.NEXT_PUBLIC_GOOGLE_API_TOKEN || '',
    cache_url:              process.env.NEXT_PUBLIC_CACHE_URL || './tmp/',
    password:               process.env.NEXT_PUBLIC_PASSWORD || 'admin',
    supaBaseUrl:            process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    supaBasePublicKey:      process.env.NEXT_PUBLIC_SUPABASE_KEY || '',
    supaBaseTable:          process.env.NEXT_PUBLIC_SUPABASE_TABLE || 'dev_companies',
    supaBaseLogs:           process.env.NEXT_PUBLIC_SUPABASE_LOGS_TABLE || 'dev_logs',
    apify_url:              process.env.NEXT_PUBLIC_APIFY_URL || 'https://api.apify.com/v2/acts/',
    apify_token:            process.env.NEXT_PUBLIC_APIFY_TOKEN || ''
}
